services:
  empresa_a:
    build: .
    container_name: empresa_a
    environment:
      - NOME_EMPRESA=empresa_a
      - PORTA=8085
      - RPC_URL=http://host.docker.internal:8545
      - CONTRACT_ADDRESS=5FbDB2315678afecb367f032d93F642f64180aa3
      - PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - CHAIN_ID=31337
    ports:
      - "8085:8085"
    networks:
      - default

  empresa_b:
    build: .
    container_name: empresa_b
    environment:
      - NOME_EMPRESA=empresa_b
      - PORTA=8086
      - RPC_URL=http://host.docker.internal:8546
      - CONTRACT_ADDRESS=5FbDB2315678afecb367f032d93F642f64180aa3
      - PRIVATE_KEY=59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      - CHAIN_ID=31337
    ports:
      - "8086:8086"
    networks:
      - default

  empresa_c:
    build: .
    container_name: empresa_c
    environment:
      - NOME_EMPRESA=empresa_c
      - PORTA=8087
      - RPC_URL=http://host.docker.internal:8547
      - CONTRACT_ADDRESS=5FbDB2315678afecb367f032d93F642f64180aa3
      - PRIVATE_KEY=5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
      - CHAIN_ID=31337
    ports:
      - "8087:8087"
    networks:
      - default

  carro_cliente:
    build:
      context: .
      dockerfile: Dockerfile.carro_cliente
    container_name: carro_cliente
    environment:
      - SERVER_URL=http://empresa_a:8085
    depends_on:
      - empresa_a
    networks:
      - default

networks:
  default:
    driver: bridge