version: "3.9"

services:
  empresa_a:
    build:
      context: .
      dockerfile: empresa_a/Dockerfile
    ports:
      - "8081:8081"
    container_name: empresa_a

  empresa_b:
    build:
      context: .
      dockerfile: empresa_b/Dockerfile
    ports:
      - "8082:8082"
    container_name: empresa_b

  empresa_c:
    build:
      context: .
      dockerfile: empresa_c/Dockerfile
    ports:
      - "8083:8083"
    container_name: empresa_c
